export interface Verse {
  text: string;
  reference: string;
}

function dayOfYear(date: Date = new Date()): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

const FALLBACK_VERSE: Verse = {
  text: 'Cast all your anxiety on him because he cares for you.',
  reference: '1 Peter 5:7',
};

export const verses: Verse[] = [
  { text: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.', reference: 'Jeremiah 29:11' },
  { text: 'I can do all this through him who gives me strength.', reference: 'Philippians 4:13' },
  { text: 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.', reference: 'Proverbs 3:5-6' },
  { text: 'The Lord is my shepherd, I lack nothing.', reference: 'Psalm 23:1' },
  { text: 'Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.', reference: 'Joshua 1:9' },
  { text: 'Come to me, all you who are weary and burdened, and I will give you rest.', reference: 'Matthew 11:28' },
  { text: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.', reference: 'John 3:16' },
  { text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.', reference: 'Philippians 4:6' },
  { text: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.', reference: 'Romans 8:28' },
  { text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.', reference: 'Psalm 34:18' },
  { text: 'Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken.', reference: 'Psalm 55:22' },
  { text: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God.', reference: 'Romans 8:38-39' },
  { text: 'He gives strength to the weary and increases the power of the weak.', reference: 'Isaiah 40:29' },
  { text: 'But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.', reference: 'Isaiah 40:31' },
  { text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.', reference: 'John 14:27' },
  { text: 'The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.', reference: 'Lamentations 3:22-23' },
  { text: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.', reference: 'Matthew 7:7' },
  { text: 'I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.', reference: 'Psalm 139:14' },
  { text: 'Be still, and know that I am God.', reference: 'Psalm 46:10' },
  { text: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.', reference: '1 Corinthians 13:4' },
  { text: 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.', reference: 'James 1:5' },
  { text: 'The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.', reference: 'Numbers 6:24-25' },
  { text: 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.', reference: '2 Timothy 1:7' },
  { text: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.', reference: 'Matthew 6:33' },
  { text: 'I have been crucified with Christ and I no longer live, but Christ lives in me.', reference: 'Galatians 2:20' },
  { text: 'Rejoice always, pray continually, give thanks in all circumstances; for this is God\'s will for you in Christ Jesus.', reference: '1 Thessalonians 5:16-18' },
  { text: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', reference: 'Psalm 51:10' },
  { text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.', reference: 'Galatians 6:9' },
  { text: 'Your word is a lamp for my feet, a light on my path.', reference: 'Psalm 119:105' },
  { text: 'With God all things are possible.', reference: 'Matthew 19:26' },
  { text: 'I lift up my eyes to the mountains — where does my help come from? My help comes from the Lord, the Maker of heaven and earth.', reference: 'Psalm 121:1-2' },
  { text: 'Delight yourself in the Lord, and he will give you the desires of your heart.', reference: 'Psalm 37:4' },
  { text: 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.', reference: '1 Corinthians 10:13' },
  { text: 'Humble yourselves, therefore, under God\'s mighty hand, that he may lift you up in due time.', reference: '1 Peter 5:6' },
  { text: 'For we live by faith, not by sight.', reference: '2 Corinthians 5:7' },
  { text: 'Greater love has no one than this: to lay down one\'s life for one\'s friends.', reference: 'John 15:13' },
  { text: 'The Lord is my light and my salvation — whom shall I fear?', reference: 'Psalm 27:1' },
  { text: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.', reference: 'Galatians 5:22-23' },
  { text: 'I will never leave you nor forsake you.', reference: 'Hebrews 13:5' },
  { text: 'In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us.', reference: 'Romans 8:26' },
  { text: 'For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you.', reference: 'Isaiah 41:13' },
  { text: 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.', reference: 'Philippians 4:19' },
  { text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', reference: 'Psalm 23:4' },
  { text: 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.', reference: 'Isaiah 26:3' },
  { text: 'The prayer of a righteous person is powerful and effective.', reference: 'James 5:16' },
  { text: 'Now faith is confidence in what we hope for and assurance about what we do not see.', reference: 'Hebrews 11:1' },
  { text: 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.', reference: 'Ephesians 2:8' },
  { text: 'Let the morning bring me word of your unfailing love, for I have put my trust in you.', reference: 'Psalm 143:8' },
  { text: 'The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge.', reference: 'Psalm 18:2' },
  { text: 'This is the day the Lord has made; let us rejoice and be glad in it.', reference: 'Psalm 118:24' },
  { text: 'He heals the brokenhearted and binds up their wounds.', reference: 'Psalm 147:3' },
  { text: 'I sought the Lord, and he answered me; he delivered me from all my fears.', reference: 'Psalm 34:4' },
  { text: 'May the God of hope fill you with all joy and peace as you trust in him.', reference: 'Romans 15:13' },
  { text: 'God is our refuge and strength, an ever-present help in trouble.', reference: 'Psalm 46:1' },
  { text: 'Before I formed you in the womb I knew you, before you were born I set you apart.', reference: 'Jeremiah 1:5' },
  { text: 'The Lord is compassionate and gracious, slow to anger, abounding in love.', reference: 'Psalm 103:8' },
  { text: 'We love because he first loved us.', reference: '1 John 4:19' },
  { text: 'I waited patiently for the Lord; he turned to me and heard my cry.', reference: 'Psalm 40:1' },
  { text: 'See what great love the Father has lavished on us, that we should be called children of God!', reference: '1 John 3:1' },
  { text: 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights.', reference: 'James 1:17' },
  { text: 'I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.', reference: 'John 16:33' },
  { text: 'Let us then approach God\'s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.', reference: 'Hebrews 4:16' },
  { text: 'For where two or three gather in my name, there am I with them.', reference: 'Matthew 18:20' },
  { text: 'Taste and see that the Lord is good; blessed is the one who takes refuge in him.', reference: 'Psalm 34:8' },
  { text: 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.', reference: 'Psalm 73:26' },
  { text: 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!', reference: '2 Corinthians 5:17' },
  { text: 'Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.', reference: 'Colossians 3:13' },
  { text: 'Surely goodness and love will follow me all the days of my life, and I will dwell in the house of the Lord forever.', reference: 'Psalm 23:6' },
  { text: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.', reference: 'Romans 12:2' },
  { text: 'Blessed are the pure in heart, for they will see God.', reference: 'Matthew 5:8' },
  { text: 'Fear not, for I have redeemed you; I have summoned you by name; you are mine.', reference: 'Isaiah 43:1' },
  { text: 'He who began a good work in you will carry it on to completion until the day of Christ Jesus.', reference: 'Philippians 1:6' },
  { text: 'Give thanks to the Lord, for he is good; his love endures forever.', reference: 'Psalm 107:1' },
  { text: 'Submit yourselves, then, to God. Resist the devil, and he will flee from you. Come near to God and he will come near to you.', reference: 'James 4:7-8' },
  { text: 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.', reference: 'Psalm 32:8' },
  { text: 'You are the light of the world. A town built on a hill cannot be hidden.', reference: 'Matthew 5:14' },
  { text: 'Finally, be strong in the Lord and in his mighty power.', reference: 'Ephesians 6:10' },
  { text: 'The Lord will fight for you; you need only to be still.', reference: 'Exodus 14:14' },
  { text: 'My grace is sufficient for you, for my power is made perfect in weakness.', reference: '2 Corinthians 12:9' },
  { text: 'He wakens me morning by morning, wakens my ear to listen like one being instructed.', reference: 'Isaiah 50:4' },
  { text: 'I will praise you, Lord my God, with all my heart; I will glorify your name forever.', reference: 'Psalm 86:12' },
  { text: 'We have this hope as an anchor for the soul, firm and secure.', reference: 'Hebrews 6:19' },
  { text: 'The Lord is good, a refuge in times of trouble. He cares for those who trust in him.', reference: 'Nahum 1:7' },
  { text: 'My soul finds rest in God alone; my salvation comes from him.', reference: 'Psalm 62:1' },
  { text: 'For we are God\'s handiwork, created in Christ Jesus to do good works.', reference: 'Ephesians 2:10' },
  { text: 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.', reference: 'John 15:5' },
  { text: 'Blessed is the one who trusts in the Lord, whose confidence is in him.', reference: 'Jeremiah 17:7' },
  { text: 'For the word of God is alive and active. Sharper than any double-edged sword.', reference: 'Hebrews 4:12' },
  { text: 'In their hearts humans plan their course, but the Lord establishes their steps.', reference: 'Proverbs 16:9' },
  { text: 'The Lord will guide you always; he will satisfy your needs in a sun-scorched land.', reference: 'Isaiah 58:11' },
  { text: 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.', reference: 'Ephesians 3:20' },
  { text: 'Satisfy us in the morning with your unfailing love, that we may sing for joy and be glad all our days.', reference: 'Psalm 90:14' },
  { text: 'Commit your works to the Lord, and your plans will be established.', reference: 'Proverbs 16:3' },
  { text: 'In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.', reference: 'Psalm 4:8' },
  { text: 'The Lord is my strength and my shield; my heart trusts in him, and he helps me.', reference: 'Psalm 28:7' },
  { text: 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.', reference: 'Psalm 91:1' },
  { text: 'The Lord is my portion; therefore I will wait for him.', reference: 'Lamentations 3:24' },
  { text: 'Blessed are those who hunger and thirst for righteousness, for they will be filled.', reference: 'Matthew 5:6' },
  { text: 'A new command I give you: Love one another. As I have loved you, so you must love one another.', reference: 'John 13:34' },
  { text: 'And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', reference: 'Philippians 4:7' },
  { text: 'The Lord is righteous in all his ways and faithful in all he does.', reference: 'Psalm 145:17' },
  { text: 'Because of the Lord\'s great love we are not consumed, for his compassions never fail.', reference: 'Lamentations 3:22' },
  { text: 'Not by might nor by power, but by my Spirit, says the Lord Almighty.', reference: 'Zechariah 4:6' },
  { text: 'For you created my inmost being; you knit me together in my mother\'s womb.', reference: 'Psalm 139:13' },
  { text: 'He is before all things, and in him all things hold together.', reference: 'Colossians 1:17' },
  { text: 'Draw near to God and He will draw near to you.', reference: 'James 4:8' },
  { text: 'If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you.', reference: 'John 15:7' },
  { text: 'Do not let your hearts be troubled. You believe in God; believe also in me.', reference: 'John 14:1' },
  { text: 'Wait for the Lord; be strong and take heart and wait for the Lord.', reference: 'Psalm 27:14' },
  { text: 'The Lord appeared to us in the past, saying: "I have loved you with an everlasting love; I have drawn you with unfailing kindness."', reference: 'Jeremiah 31:3' },
  { text: 'For to me, to live is Christ and to die is gain.', reference: 'Philippians 1:21' },
  { text: 'Blessed are the peacemakers, for they will be called children of God.', reference: 'Matthew 5:9' },
  { text: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.', reference: 'Colossians 3:23' },
  { text: 'The righteous person may have many troubles, but the Lord delivers him from them all.', reference: 'Psalm 34:19' },
  { text: 'The joy of the Lord is your strength.', reference: 'Nehemiah 8:10' },
  { text: 'Though the fig tree does not bud and there are no grapes on the vines, yet I will rejoice in the Lord.', reference: 'Habakkuk 3:17-18' },
  { text: 'Weeping may stay for the night, but rejoicing comes in the morning.', reference: 'Psalm 30:5' },
  { text: 'You will seek me and find me when you seek me with all your heart.', reference: 'Jeremiah 29:13' },
  { text: 'A generous person will prosper; whoever refreshes others will be refreshed.', reference: 'Proverbs 11:25' },
  { text: 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day.', reference: '2 Corinthians 4:16' },
  { text: 'He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield.', reference: 'Psalm 91:4' },
  { text: 'From the rising of the sun to the place where it sets, the name of the Lord is to be praised.', reference: 'Psalm 113:3' },
  { text: 'As far as the east is from the west, so far has he removed our transgressions from us.', reference: 'Psalm 103:12' },
  { text: 'Do not be overcome by evil, but overcome evil with good.', reference: 'Romans 12:21' },
  { text: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.', reference: 'Romans 5:8' },
  { text: 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.', reference: '2 Timothy 3:16' },
  { text: 'Let us hold unswervingly to the hope we profess, for he who promised is faithful.', reference: 'Hebrews 10:23' },
  { text: 'Praise the Lord, my soul, and forget not all his benefits.', reference: 'Psalm 103:2' },
  { text: 'He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.', reference: 'Micah 6:8' },
  { text: 'Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely — think about such things.', reference: 'Philippians 4:8' },
  { text: 'We are hard pressed on every side, but not crushed; perplexed, but not in despair.', reference: '2 Corinthians 4:8' },
  { text: 'He has made everything beautiful in its time.', reference: 'Ecclesiastes 3:11' },
  { text: 'He who goes out weeping, carrying seed to sow, will return with songs of joy.', reference: 'Psalm 126:6' },
  { text: 'But I trust in your unfailing love; my heart rejoices in your salvation.', reference: 'Psalm 13:5' },
  { text: 'I am the way and the truth and the life. No one comes to the Father except through me.', reference: 'John 14:6' },
  { text: 'And now these three remain: faith, hope and love. But the greatest of these is love.', reference: '1 Corinthians 13:13' },
  { text: 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.', reference: 'Ephesians 2:8-9' },
  { text: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over.', reference: 'Luke 6:38' },
  { text: 'Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.', reference: 'Matthew 5:16' },
  { text: 'Let us run with perseverance the race marked out for us, fixing our eyes on Jesus, the pioneer and perfecter of faith.', reference: 'Hebrews 12:1-2' },
  { text: 'For the Lord is good and his love endures forever; his faithfulness continues through all generations.', reference: 'Psalm 100:5' },
  { text: 'And I heard a loud voice from the throne saying, "Look! God\'s dwelling place is now among the people, and he will dwell with them."', reference: 'Revelation 21:3' },
  { text: 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End.', reference: 'Revelation 22:13' },
  { text: 'The Lord loves the righteous.', reference: 'Psalm 146:8' },
  { text: 'Blessed are they that dwell in thy house: ever singing thy praise.', reference: 'Psalm 84:4' },
  { text: 'The heavens declare the glory of God; the skies proclaim the work of his hands.', reference: 'Psalm 19:1' },
  { text: 'I will sing of the Lord\'s great love forever; with my mouth I will make your faithfulness known through all generations.', reference: 'Psalm 89:1' },
  { text: 'Hear my cry, O God; listen to my prayer.', reference: 'Psalm 61:1' },
  { text: 'The Lord is nigh unto all them that call upon him, to all that call upon him in truth.', reference: 'Psalm 145:18' },
  { text: 'Serve the Lord with gladness: come before his presence with singing.', reference: 'Psalm 100:2' },
  { text: 'Know that the Lord hath set apart him that is godly for himself.', reference: 'Psalm 4:3' },
  { text: 'The Lord is in his holy temple: the Lord\'s throne is in heaven.', reference: 'Psalm 11:4' },
  { text: 'Keep me as the apple of the eye, hide me under the shadow of thy wings.', reference: 'Psalm 17:8' },
  { text: 'Blessed be the Lord, who daily loadeth us with benefits.', reference: 'Psalm 68:19' },
  { text: 'Make a joyful noise unto the Lord, all ye earth.', reference: 'Psalm 100:1' },
  { text: 'I have set the Lord always before me: because he is at my right hand, I shall not be moved.', reference: 'Psalm 16:8' },
  { text: 'Seek the Lord while he may be found, call upon him while he is near.', reference: 'Isaiah 55:6' },
  { text: 'I will lift up mine eyes unto the hills, from whence cometh my help.', reference: 'Psalm 121:1' },
  { text: 'Thou art my God, and I will praise thee: thou art my God, I will exalt thee.', reference: 'Psalm 118:28' },
  { text: 'It is a good thing to give thanks unto the Lord, and to sing praises unto thy name.', reference: 'Psalm 92:1' },
  { text: 'Let the beauty of the Lord our God be upon us.', reference: 'Psalm 90:17' },
  { text: 'For as the heavens are higher than the earth, so are my ways higher than your ways.', reference: 'Isaiah 55:9' },
  { text: 'He that hath ears to hear, let him hear.', reference: 'Matthew 11:15' },
  { text: 'Therefore take no thought for the morrow: for the morrow shall take thought for the things of itself.', reference: 'Matthew 6:34' },
  { text: 'And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger.', reference: 'John 6:35' },
  { text: 'Thou hast made known to me the ways of life; thou shalt make me full of joy with thy countenance.', reference: 'Acts 2:28' },
  { text: 'Therefore keep watch, because you do not know on what day your Lord will come.', reference: 'Matthew 24:42' },
  { text: 'Therefore, as God\'s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.', reference: 'Colossians 3:12' },
  { text: 'And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.', reference: '2 Corinthians 9:8' },
  { text: 'Trust in the Lord with all your heart and lean not on your own understanding.', reference: 'Proverbs 3:5' },
  { text: 'But the Counselor, the Holy Spirit, whom the Father will send in my name, will teach you all things.', reference: 'John 14:26' },
  { text: 'Therefore each of you must put off falsehood and speak truthfulness to your neighbor, for we are all members of one body.', reference: 'Ephesians 4:25' },
  { text: 'All the days ordained for me were written in your book before one of them came to be.', reference: 'Psalm 139:16' },
  { text: 'Therefore, my dear brothers and sisters, be firm. Let nothing move you. Always give yourselves fully to the work of the Lord.', reference: '1 Corinthians 15:58' },
  { text: 'Therefore, I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.', reference: 'Mark 11:24' },
  { text: 'Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort.', reference: '2 Corinthians 1:3' },
  { text: 'For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.', reference: '2 Corinthians 4:17' },
  { text: 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders.', reference: 'Hebrews 12:1' },
  { text: 'The Lord is my helper; I will not be afraid. What can mere mortals do to me?', reference: 'Hebrews 13:6' },
  { text: 'Now we see only a reflection as in a mirror; then we shall see face to face.', reference: '1 Corinthians 13:12' },
  { text: 'Because of the service by which you have proved yourselves, men will praise God for the obedience that accompanies your confession.', reference: '2 Corinthians 9:13' },
  { text: 'So then, just as you received Christ Jesus as Lord, continue to live your lives in him.', reference: 'Colossians 2:6' },
  { text: 'The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding.', reference: 'Proverbs 9:10' },
  { text: 'Many are the plans in a man\'s heart, but it is the Lord\'s purpose that prevails.', reference: 'Proverbs 19:21' },
  { text: 'Praise the Lord. Give thanks to the Lord, for he is good; his love endures forever.', reference: 'Psalm 106:1' },
  { text: 'The Lord is gracious and righteous; our God is full of compassion.', reference: 'Psalm 116:5' },
  { text: 'Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.', reference: 'Psalm 100:4' },
  { text: 'You make known to me the path of life; you will fill me with joy in your presence.', reference: 'Psalm 16:11' },
  { text: 'In my distress I called to the Lord, and he answered me.', reference: 'Psalm 120:1' },
  { text: 'The Lord is my strength and my song; he has become my salvation.', reference: 'Psalm 118:14' },
  { text: 'For the eyes of the Lord range throughout the earth to strengthen those whose hearts are fully committed to him.', reference: '2 Chronicles 16:9' },
  { text: 'Blessed is the man who fears the Lord, who finds great delight in his commands.', reference: 'Psalm 112:1' },
  { text: 'Be merciful to me, O God, be merciful to me, for in you I take refuge.', reference: 'Psalm 57:1' },
  { text: 'The Lord sustains all those who fall and lifts up all who are bowed down.', reference: 'Psalm 145:14' },
  { text: 'How precious to me are your thoughts, God! How vast is the sum of them!', reference: 'Psalm 139:17' },
  { text: 'My help comes from the Lord, the Maker of heaven and earth.', reference: 'Psalm 121:2' },
  { text: 'You are forgiving and good, O Lord, abounding in love to all who call to you.', reference: 'Psalm 86:5' },
  { text: 'Acknowledge and take to heart this day that the Lord is God in heaven above and on the earth below.', reference: 'Deuteronomy 4:39' },
  { text: 'The Lord has made his salvation known and revealed his righteousness to the nations.', reference: 'Psalm 98:2' },
  { text: 'You are the God who performs miracles; you display your power among the peoples.', reference: 'Psalm 77:14' },
  { text: 'All the faithful will praise you, Lord; they will sing of the ways of the Lord.', reference: 'Psalm 138:5' },
  { text: 'He will have no fear of bad news; his heart is steadfast, trusting in the Lord.', reference: 'Psalm 112:7' },
  { text: 'The Lord your God is with you, he is mighty to save. He will take great delight in you, he will quiet you with his love.', reference: 'Zephaniah 3:17' },
  { text: 'May your unfailing love rest upon us, O Lord, even as we put our hope in you.', reference: 'Psalm 33:22' },
  { text: 'My soul yearns, even faints, for the courts of the Lord; my heart and my flesh cry out for the living God.', reference: 'Psalm 84:2' },
  { text: 'Better is one day in your courts than a thousand elsewhere; I would rather be a doorkeeper in the house of my God.', reference: 'Psalm 84:10' },
  { text: 'Blessed are those whose strength is in you, who have set their hearts on pilgrimage.', reference: 'Psalm 84:5' },
  { text: 'The Lord will perfect that which concerneth me: thy mercy, O Lord, endureth for ever.', reference: 'Psalm 138:8' },
  { text: 'Surely the Lord God will do nothing, but he revealeth his secret unto his servants the prophets.', reference: 'Amos 3:7' },
  { text: 'O Lord, thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things.', reference: 'Isaiah 25:1' },
  { text: 'Who is like unto the Lord our God, who dwelleth on high, who humbleth himself to behold the things that are in heaven?', reference: 'Psalm 113:5-6' },
  { text: 'As for me and my house, we will serve the Lord.', reference: 'Joshua 24:15' },
  { text: 'No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn.', reference: 'Isaiah 54:17' },
  { text: 'I will praise thee with my whole heart: before the gods will I sing praise unto thee.', reference: 'Psalm 138:1' },
  { text: 'Blessed be the Lord my strength which teacheth my hands to war, and my fingers to fight.', reference: 'Psalm 144:1' },
  { text: 'The Lord reigneth; let the earth rejoice; let the multitude of isles be glad thereof.', reference: 'Psalm 97:1' },
  { text: 'O sing unto the Lord a new song; for he hath done marvellous things.', reference: 'Psalm 98:1' },
  { text: 'For as the heaven is high above the earth, so great is his mercy toward them that fear him.', reference: 'Psalm 103:11' },
  { text: 'Like as a father pitieth his children, so the Lord pitieth them that fear him.', reference: 'Psalm 103:13' },
  { text: 'The mercy of the Lord is from everlasting to everlasting upon them that fear him.', reference: 'Psalm 103:17' },
  { text: 'Bless the Lord, O my soul: and all that is within me, bless his holy name.', reference: 'Psalm 103:1' },
  { text: 'Who forgiveth all thine iniquities; who healeth all thy diseases.', reference: 'Psalm 103:3' },
  { text: 'Who redeemeth thy life from destruction; who crowneth thee with lovingkindness and tender mercies.', reference: 'Psalm 103:4' },
  { text: 'Who satisfieth thy mouth with good things; so that thy youth is renewed like the eagle\'s.', reference: 'Psalm 103:5' },
  { text: 'And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us.', reference: '1 John 5:14' },
  { text: 'Commit thy way unto the Lord; trust also in him; and he shall bring it to pass.', reference: 'Psalm 37:5' },
  { text: 'And he shall bring forth thy righteousness as the light, and thy judgment as the noonday.', reference: 'Psalm 37:6' },
  { text: 'Rest in the Lord, and wait patiently for him: fret not thyself because of him who prospereth in his way.', reference: 'Psalm 37:7' },
  { text: 'For yet a little while, and the wicked shall not be: yea, thou shalt diligently consider his place, and it shall not be.', reference: 'Psalm 37:10' },
  { text: 'But the meek shall inherit the earth; and shall delight themselves in the abundance of peace.', reference: 'Psalm 37:11' },
  { text: 'The righteous shall inherit the land, and dwell therein for ever.', reference: 'Psalm 37:29' },
  { text: 'The salvation of the righteous is of the Lord: he is their strength in the time of trouble.', reference: 'Psalm 37:39' },
  { text: 'And the Lord shall help them, and deliver them: he shall deliver them from the wicked.', reference: 'Psalm 37:40' },
  { text: 'For his merciful kindness is great toward us: and the truth of the Lord endureth for ever.', reference: 'Psalm 117:2' },
  { text: 'Praise the Lord, all ye nations: praise him, all ye people.', reference: 'Psalm 117:1' },
  { text: 'O Lord, my strength and my fortress, my refuge in the day of affliction.', reference: 'Jeremiah 16:19' },
  { text: 'But thou, O Lord, art a shield for me; my glory, and the lifter up of mine head.', reference: 'Psalm 3:3' },
  { text: 'I cried unto the Lord with my voice, and he heard me out of his holy hill.', reference: 'Psalm 3:4' },
  { text: 'I laid me down and slept; I awaked; for the Lord sustained me.', reference: 'Psalm 3:5' },
  { text: 'I will not be afraid of ten thousands of people, that have set themselves against me round about.', reference: 'Psalm 3:6' },
  { text: 'Arise, O Lord; save me, O my God: for thou hast smitten all mine enemies upon the cheek bone; thou hast broken the teeth of the ungodly.', reference: 'Psalm 3:7' },
  { text: 'Salvation belongeth unto the Lord: thy blessing is upon thy people.', reference: 'Psalm 3:8' },
  { text: 'Therefore turn thou to thy God: keep mercy and judgment, and wait on thy God continually.', reference: 'Hosea 12:6' },
  { text: 'To know you is eternal life.', reference: 'John 17:3' },
  { text: 'And this is his command: to believe in the name of his Son, Jesus Christ, and to love one another as he commanded us.', reference: '1 John 3:23' },
  { text: 'Anyone who loves their father or mother more than me is not worthy of me; anyone who loves their son or daughter more than me is not worthy of me.', reference: 'Matthew 10:37' },
  { text: 'Whoever wants to be my disciple must deny themselves and take up their cross and follow me.', reference: 'Matthew 16:24' },
  { text: 'For whoever wants to save their life will lose it, but whoever loses their life for me will find it.', reference: 'Matthew 16:25' },
  { text: 'What good is it for someone to gain the whole world, yet forfeit their soul?', reference: 'Matthew 16:26' },
  { text: 'For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.', reference: 'Matthew 7:8' },
  { text: 'Which of you, if your son asks for bread, will give him a stone?', reference: 'Matthew 7:9' },
  { text: 'Or if he asks for a fish, will give him a snake?', reference: 'Matthew 7:10' },
  { text: 'If you, then, though you are evil, know how to give good gifts to your children, how much more will your Father in heaven give good gifts to those who ask him!', reference: 'Matthew 7:11' },
  { text: 'So in everything, do to others what you would have them do to you, for this is the Law and the Prophets.', reference: 'Matthew 7:12' },
  { text: 'For the mouth speaks what the heart is full of.', reference: 'Matthew 12:34' },
  { text: 'Blessed are the poor in spirit, for theirs is the kingdom of heaven.', reference: 'Matthew 5:3' },
  { text: 'Blessed are those who mourn, for they will be comforted.', reference: 'Matthew 5:4' },
  { text: 'Blessed are the meek, for they will inherit the earth.', reference: 'Matthew 5:5' },
  { text: 'Blessed are the merciful, for they will be shown mercy.', reference: 'Matthew 5:7' },
  { text: 'Blessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven.', reference: 'Matthew 5:10' },
  { text: 'You are the salt of the earth. But if the salt loses its saltiness, how can it be made salty again?', reference: 'Matthew 5:13' },
  { text: 'Neither do people light a lamp and put it under a bowl. Instead they put it on its stand, and it gives light to everyone in the house.', reference: 'Matthew 5:15' },
  { text: 'Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them.', reference: 'Matthew 5:17' },
  { text: 'By this everyone will know that you are my disciples, if you love one another.', reference: 'John 13:35' },
  { text: 'Jesus answered, "Very truly I tell you, no one can see the kingdom of God unless they are born again."', reference: 'John 3:3' },
  { text: 'For God did not send his Son into the world to condemn the world, but to save the world through him.', reference: 'John 3:17' },
  { text: 'But because of his great love for us, God, who is rich in mercy, made us alive with Christ even when we were dead in our transgressions.', reference: 'Ephesians 2:4-5' },
  { text: 'Not by works, so that no one can boast.', reference: 'Ephesians 2:9' },
  { text: 'I pray that the eyes of your heart may be enlightened in order that you may know the hope to which he has called you.', reference: 'Ephesians 1:18' },
  { text: 'And I pray that you, being rooted and established in love, may have power, together with all the Lord\'s holy people, to grasp how wide and long and high and deep is the love of Christ.', reference: 'Ephesians 3:17-18' },
  { text: 'And to know this love that surpasses knowledge—that you may be filled to the measure of all the fullness of God.', reference: 'Ephesians 3:19' },
  { text: 'To him be glory in the church and in Christ Jesus throughout all generations, for ever and ever! Amen.', reference: 'Ephesians 3:21' },
  { text: 'Therefore I urge you, brothers and sisters, in view of God\'s mercy, to offer your bodies as a living sacrifice, holy and pleasing to God.', reference: 'Romans 12:1' },
  { text: 'For just as each of us has one body with many members, and these members do not all have the same function.', reference: 'Romans 12:4' },
  { text: 'So in Christ we, though many, form one body, and each member belongs to all the others.', reference: 'Romans 12:5' },
  { text: 'We have different gifts, according to the grace given to each of us.', reference: 'Romans 12:6' },
  { text: 'If it is serving, then serve; if it is teaching, then teach.', reference: 'Romans 12:7' },
  { text: 'If it is to encourage, then give encouragement; if it is giving, then give generously; if it is to lead, do it diligently; if it is to show mercy, do it cheerfully.', reference: 'Romans 12:8' },
  { text: 'Let no debt remain outstanding, except the continuing debt to love one another, for whoever loves others has fulfilled the law.', reference: 'Romans 13:8' },
  { text: 'The commandments, "You shall not commit adultery," "You shall not murder," "You shall not steal," "You shall not covet," and whatever other command there may be, are summed up in this one command: "Love your neighbor as yourself."', reference: 'Romans 13:9' },
  { text: 'Love does no harm to a neighbor. Therefore love is the fulfillment of the law.', reference: 'Romans 13:10' },
  { text: 'Be joyful in hope, patient in affliction, faithful in prayer.', reference: 'Romans 12:12' },
  { text: 'Share with the Lord\'s people who are in need. Practice hospitality.', reference: 'Romans 12:13' },
  { text: 'Bless those who persecute you; bless and do not curse.', reference: 'Romans 12:14' },
  { text: 'Rejoice with those who rejoice; mourn with those who mourn.', reference: 'Romans 12:15' },
  { text: 'Live in harmony with one another. Do not be proud, but be willing to associate with people of low position.', reference: 'Romans 12:16' },
  { text: 'Do not repay anyone evil for evil. Be careful to do what is right in the eyes of everyone.', reference: 'Romans 12:17' },
  { text: 'If it is possible, as far as it depends on you, live at peace with everyone.', reference: 'Romans 12:18' },
  { text: 'Do not take revenge, my dear friends, but leave room for God\'s wrath, for it is written: "It is mine to avenge; I will repay," says the Lord.', reference: 'Romans 12:19' },
  { text: 'On the contrary: "If your enemy is hungry, feed him; if he is thirsty, give him something to drink. In doing this, you will heap burning coals on his head."', reference: 'Romans 12:20' },
  { text: 'But I tell you, love your enemies and pray for those who persecute you.', reference: 'Matthew 5:44' },
  { text: 'Blessed are you when people insult you, persecute you and falsely say all kinds of evil against you because of me.', reference: 'Matthew 5:11' },
  { text: 'Rejoice and be glad, because great is your reward in heaven, for in the same way they persecuted the prophets who were before you.', reference: 'Matthew 5:12' },
  { text: 'But I say to you that listen, Love your enemies, do good to those who hate you.', reference: 'Luke 6:27' },
  { text: 'Bless those who curse you, pray for those who abuse you.', reference: 'Luke 6:28' },
  { text: 'If you love those who love you, what credit is that to you? Even sinners love those who love them.', reference: 'Luke 6:32' },
  { text: 'But love your enemies, do good, and lend, expecting nothing in return. Your reward will be great, and you will be children of the Most High.', reference: 'Luke 6:35' },
  { text: 'Because the Lord your God goes with you to fight for you against your enemies to give you victory.', reference: 'Deuteronomy 20:4' },
  { text: 'The Lord is faithful to all his promises and loving toward all he has made.', reference: 'Psalm 145:13' },
  { text: 'The eyes of all look to you, and you give them their food at the proper time.', reference: 'Psalm 145:15' },
  { text: 'You open your hand and satisfy the desires of every living thing.', reference: 'Psalm 145:16' },
  { text: 'He fulfills the desires of those who fear him; he hears their cry and saves them.', reference: 'Psalm 145:19' },
  { text: 'The Lord watches over all who love him, but all the wicked he will destroy.', reference: 'Psalm 145:20' },
  { text: 'My mouth will speak in praise of the Lord. Let every creature praise his holy name for ever and ever.', reference: 'Psalm 145:21' },
  { text: 'How great is our Lord and how mighty his power; his understanding has no limit.', reference: 'Psalm 147:5' },
  { text: 'The Lord sustains the humble but casts the wicked to the ground.', reference: 'Psalm 147:6' },
  { text: 'Sing to the Lord with grateful praise; make music to our God on the harp.', reference: 'Psalm 147:7' },
  { text: 'He covers the sky with clouds; he supplies the earth with rain and makes grass grow on the hills.', reference: 'Psalm 147:8' },
  { text: 'He provides food for the cattle and for the young ravens when they call.', reference: 'Psalm 147:9' },
  { text: 'His pleasure is not in the strength of the horse, nor his delight in the legs of the warrior.', reference: 'Psalm 147:10' },
  { text: 'The Lord delights in those who fear him, who put their hope in his unfailing love.', reference: 'Psalm 147:11' },
  { text: 'Extol the Lord, O Jerusalem; praise your God, O Zion.', reference: 'Psalm 147:12' },
  { text: 'He strengthens the bars of your gates and blesses your people within you.', reference: 'Psalm 147:13' },
  { text: 'He grants peace to your borders and satisfies you with the finest of wheat.', reference: 'Psalm 147:14' },
  { text: 'He sends his command to the earth; his word runs swiftly.', reference: 'Psalm 147:15' },
  { text: 'He spreads the snow like wool and scatters the frost like ashes.', reference: 'Psalm 147:16' },
  { text: 'He hurls down his hail like pebbles. Who can withstand his icy blast?', reference: 'Psalm 147:17' },
  { text: 'He sends his word and melts them; he stirs up his breezes, and the waters flow.', reference: 'Psalm 147:18' },
  { text: 'He has revealed his word to Jacob, his laws and decrees to Israel.', reference: 'Psalm 147:19' },
  { text: 'He has done this for no other nation; they do not know his laws.', reference: 'Psalm 147:20' },
  { text: 'O send out thy light and thy truth: let them lead me.', reference: 'Psalm 43:3' },
  { text: 'And the God of peace shall be with you.', reference: 'Philippians 4:9' },
  { text: 'Be thou faithful unto death, and I will give thee a crown of life.', reference: 'Revelation 2:10' },
  { text: 'I have fought a good fight, I have finished my course, I have kept the faith.', reference: '2 Timothy 4:7' },
  { text: 'Not rendering evil for evil, or railing for railing: but contrariwise blessing.', reference: '1 Peter 3:9' },
  { text: 'For the love of Christ constraineth us.', reference: '2 Corinthians 5:14' },
  { text: 'O magnify the Lord with me, and let us exalt his name together.', reference: 'Psalm 34:3' },
  { text: 'For his invisible things from the creation of the world are clearly seen.', reference: 'Romans 1:20' },
  { text: 'Blessed is the man that walketh not in the counsel of the ungodly.', reference: 'Psalm 1:1' },
  { text: 'The law of the Lord is perfect, converting the soul.', reference: 'Psalm 19:7' },
  { text: 'One thing have I desired of the Lord, that will I seek after.', reference: 'Psalm 27:4' },
  { text: 'O come, let us sing unto the Lord: let us make a joyful noise to the rock of our salvation.', reference: 'Psalm 95:1' },
  { text: 'The righteous also shall hold on his way, and he that hath clean hands shall wax stronger and stronger.', reference: 'Job 17:9' },
  { text: 'If we confess our sins, he is faithful and just to forgive us our sins.', reference: '1 John 1:9' },
  { text: 'I rejoiced greatly that I found of thy children walking in truth.', reference: '2 John 1:4' },
  { text: 'The grace of our Lord Jesus Christ be with you all. Amen.', reference: 'Revelation 22:21' },
  { text: 'Let your conversation be as it becometh the gospel of Christ.', reference: 'Philippians 1:27' },
  { text: 'And the very God of peace sanctify you wholly.', reference: '1 Thessalonians 5:23' },
  { text: 'And this is the record, that God hath given to us eternal life, and this life is in his Son.', reference: '1 John 5:11' },
  { text: 'The Lord will command his lovingkindness in the daytime, and in the night his song shall be with me.', reference: 'Psalm 42:8' },
  { text: 'Thy mercy, O Lord, is in the heavens.', reference: 'Psalm 36:5' },
  { text: 'O Lord, my God, in thee do I put my trust.', reference: 'Psalm 7:1' },
  { text: 'And ye shall know the truth, and the truth shall make you free.', reference: 'John 8:32' },
  { text: 'Not that we are sufficient of ourselves to think any thing as of ourselves.', reference: '2 Corinthians 3:5' },
  { text: 'There is therefore now no condemnation to them which are in Christ Jesus.', reference: 'Romans 8:1' },
  { text: 'For we wrestle not against flesh and blood, but against principalities, against powers.', reference: 'Ephesians 6:12' },
  { text: 'Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.', reference: 'Ephesians 6:11' },
  { text: 'What shall we then say to these things? If God be for us, who can be against us?', reference: 'Romans 8:31' },
  { text: 'Beloved, if God so loved us, we ought also to love one another.', reference: '1 John 4:11' },
  { text: 'For Christ is the end of the law for righteousness to every one that believeth.', reference: 'Romans 10:4' },
  { text: 'But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ.', reference: 'Ephesians 2:13' },
  { text: 'And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.', reference: 'Matthew 21:22' },
  { text: 'For the Father himself loveth you, because ye have loved me, and have believed that I came out from God.', reference: 'John 16:27' },
  { text: 'I am come that they might have life, and that they might have it more abundantly.', reference: 'John 10:10' },
  { text: 'That as sin hath reigned unto death, even so might grace reign through righteousness unto eternal life by Jesus Christ.', reference: 'Romans 5:21' },
  { text: 'Verily, verily, I say unto you, He that hath ears to hear, let him hear.', reference: 'Mark 4:9' },
  { text: 'So when this corruptible shall have put on incorruption, and this mortal shall have put on immortality.', reference: '1 Corinthians 15:54' },
  { text: 'But the gift of God is eternal life through Jesus Christ our Lord.', reference: 'Romans 6:23' },
  { text: 'And he said unto them, Go ye into all the world, and preach the gospel to every creature.', reference: 'Mark 16:15' },
  { text: 'Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.', reference: 'Matthew 28:19' },
  { text: 'For the Lord loves the just and will not forsake his faithful ones.', reference: 'Psalm 37:28' },
  { text: 'He who walks with the wise grows wise, but a companion of fools suffers harm.', reference: 'Proverbs 13:20' },
  { text: 'However, each one of you also must love his wife as he loves himself, and the wife must respect her husband.', reference: 'Ephesians 5:33' },
  { text: 'Jesus said, "Let the little children come to me, and do not hinder them, for the kingdom of heaven belongs to such as these."', reference: 'Matthew 19:14' },
  { text: 'Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.', reference: 'John 11:25' },
];

export function getDayVerse(date?: Date): Verse {
  if (verses.length === 0) return FALLBACK_VERSE;
  const day = dayOfYear(date);
  const index = (day - 1) % verses.length;
  return verses[index];
}
